// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// myNN_lars_cpp
arma::vec myNN_lars_cpp(arma::vec x_input);
RcppExport SEXP _ahtg_myNN_lars_cpp(SEXP x_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x_input(x_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(myNN_lars_cpp(x_input));
    return rcpp_result_gen;
END_RCPP
}
// myNN_glmnet_cpp
arma::vec myNN_glmnet_cpp(arma::vec x_input);
RcppExport SEXP _ahtg_myNN_glmnet_cpp(SEXP x_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x_input(x_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(myNN_glmnet_cpp(x_input));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ahtg_myNN_lars_cpp", (DL_FUNC) &_ahtg_myNN_lars_cpp, 1},
    {"_ahtg_myNN_glmnet_cpp", (DL_FUNC) &_ahtg_myNN_glmnet_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ahtg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
